### PR TITLE
Fix reading CS status

### PR DESCRIPTION
**Pull request by georgekontogiorgos**
I was trying to create a virtual motor in order to drive a slit setup with Power PMAC, then I came across the problem that the DMOV was not returning to stop condition. 

I studied the code and debug it. I find out that the `callback` function on `pmacCSController.cpp` file never pass through the if that compare type with a constant due to their different values. 

I printed the `type` variable and its value is 2, which means that a fast read call this function, not pre fast read.

This solution solved my problem, so I am creating this pull request to collaborate with this driver. I would appreciate if you consider my request.

I could be wrong on my hypothesis that it is a fast read, not a pre fast read. Maybe we need to change `type` value, not the constant.

In case of any suggestions, feel free to contact me.

### CODE REVIEW

**Comment by gilesknap** [comment]
Hi George, I'm investigating the issue with reading CS status today and will get back to you.

I can't accept the commit 'FixPaths', that is a specific fix for your own site and should be on your own branch.

**Comment by georgekontogiorgos** [comment]
Hi Giles,

I did a mistake, this FixPaths shouldn't be there, since, as you said, is an specific correction to my work site.

I didn't have time on this week to read all message, I will do it as soon as possible.

Thanks for consider my pull request and for all support that you gave me.

**Comment by gilesknap** [comment]
Hi George, 
I have not heard from you re recent versions of pmac. Did you get anywhere? Do you still think this PR is correct?

**Comment by georgekontogiorgos** [comment]
Hi Giles,
I tested today your fixes and they fix my problems.
Therefore this PR can be refused as your fixes look like better than mine (they look like more elegant way of solving this problem).
Thanks
George

**Pull request closed without merging**
